<a href="https://colab.research.google.com/github/Shahadbal/Tutoring_Python/blob/main/Python_October21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exrecises

Quick Recall

In [ ]:
#Recall
lst1=[1,2,3]
tup1=('a','b','c')
dict1={'fn':'Rania', 'ln':'Ahmad'}
for element in lst1: # 1 2 3
  print(element)
for element in tup1: #
  print(element)
for key in dict1: # dict1['fn'] = Rania
  print(key , dict1[key])
for c in dict1:
  print(c) #
for c,element in enumerate(lst1): #c will store the indices of the elements, while 'element' will hold the actual values of the elements
  print(c,element)  # 0 1
for c, element in enumerate(tup1):
  print(element)
for c, key in enumerate(dict1):
  print(c, key , dict1[key])

1
2
3
a
b
c
fn Rania
ln Ahmad
fn
ln
0 1
1 2
2 3
a
b
c
0 fn Rania
1 ln Ahmad


In [ ]:
stu_name = ['Ahmad', 'Reem', 'Fatima']
for c,name in enumerate(stu_name):
  print(c,'\t', name)

0 	 Ahmad
1 	 Reem
2 	 Fatima


In [ ]:
#Write a program that asks the user to input, their name, age and occupation and outputs a string, "[name] is [age] years old and works as a [job]."
name = input("Enter your name: ")
age = input("Enter your age: ")
occupation = input("Enter your occupation: ")

# Create the output string
output_string = f"{name} is {age} years old and works as a {occupation}."

# Display the result
print(output_string)

Enter your name: Shahad
Enter your age: 21
Enter your occupation: Stufent
Shahad is 21 years old and works as a Stufent.


In [ ]:
#Write a program that takes a positive integer as an input and return’s it’s length. Return 0 if the number is not a positive integer.
num = -24256
# Check if the input is a positive integer
if num >=0:
    num_str = str(num) #Now we are dealing with 2456 as a string not number
    # Calculate and display the length
    length = len(num_str)
    print(f"The length of {num} is {length}.")
else:
    print("0")

0


In [ ]:
#In a single line of code extract all numbers from a list that are greater than 100.

lis1 = [30, 55, 1004 , 112.5, 33.8, 500.4, 76, 8, 200]
lis2= [element for element in lis1 if element>100] #
print(lis2)

[1004, 112.5, 500.4, 200]


In [ ]:
#In a single line of code capitalize the first character of the value strings in a Python dictionary.
my_dict = {"01": "ahmad", "02": "khalid", "03": "lama"}
capitalized_dict = {k: my_dict[k].capitalize() for c, k in enumerate(my_dict)}
print(capitalized_dict)

{'01': 'Ahmad', '02': 'Khalid', '03': 'Lama'}



# Set


## Sets

Sets are an unordered collection of *unique* elements. We can construct them by using the set() function. Let's go ahead and make a set to see how it works

In [ ]:
x = set() # set empty

In [ ]:
x.add(3) # x = {3}

In [ ]:
x.add("AI")
x.add(3)
x

{3, 'AI'}

We know that a set has only unique entries. So what happens when we try to add something that is already in a set?

In [ ]:
# Add a different element
x.add(2)
x.add('String')

In [ ]:
x

{2, 3, 'adle'}

In [ ]:
x.add(2)
print(x)

{'adle', 2, 3}


In [ ]:
li = [1,2,2,3,3,4,5,6,6,6]
unique_list = set(li) # 1, 2, 3
print(unique_list)
print(type(unique_list))
to_list = list(unique_list) #list(Varaiable)
print(to_list)
print(type(to_list))

{1, 2, 3, 4, 5, 6}
<class 'set'>
[1, 2, 3, 4, 5, 6]
<class 'list'>


## unpacking
All containers can be unpacked as follows:

In [ ]:
t = (3, 2, 1)
a, c, b= t  # unpacks the tuple t; prints "3 2 1"
print(a, b, c) #3 1 2

l = [3, 2, 1]
a, b, c = l  # unpacks the list l; prints "3 2 1"
print(a, b, c)

s = {3, 2, 1}
a, b, c = s  # unpacks the set s; prints "1 2 3" (set ordering)
print(a, b, c)

d = {'c': 3, 'b': 2, 'a': 1}
a, b, c = d  # unpacks the keys of the dict d; prints "c b a"
print(a, b, c)
ak, bk, ck = d.keys()  # unpacks the keys of the dict d; prints "c b a"
print(ak, bk, ck)
a, b, c = d.values()  # unpacks the values of the dict d; prints "3 2 1"
print(a, b, c)

3 1 2
3 2 1
1 2 3
c b a
c b a
3 2 1


In [ ]:
numbers = [1, 2, 3, 4, 5, 6]

# The left side of unpacking should be list or tuple.
*a, = numbers
# a = [1, 2, 3, 4, 5, 6]

*a, b, c = numbers
# a = [1, 2, 3, 4, 5]
# b = 6

a, *b = numbers
# a = 1
# b = [2, 3, 4, 5, 6]

a, *b, c = numbers
# a = 1
# b = [2, 3, 4, 5]
# c = 6

# Functions

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x): # if it's positive return 'Positive'
  if x>0:
    return 'Positive'
  elif   x<0:
    return "Negitive"
  else:
    return "Zero"

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

In [ ]:
for x in [-1, 0, 1]: #x=-1
    print(sign(x))
# Prints "negative", "zero", "positive"

negative
zero
positive


In [ ]:
def hello(name, loud=False):
    if loud: #loud == TRue
        print('HELLO, {}!'.format(name.upper()))
    else:
        print('Hello,', name)

hello("Bob") # Prints "Hello, Bob" loud = false
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Default
HELLO, FRED!


In [ ]:
def ell_2_norm(a,b):
    y = (a**2 + b**2)**(0.5)
    return y

In [ ]:
ell_2_norm(1,3)

3.1622776601683795

# Numpy

[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. Check out [this visual tutorial](http://jalammar.github.io/visual-numpy/).

In [ ]:
import numpy as np

In [ ]:
list1 = [1,2,3] #.max
max=0
for element in list1:
  if element > max :
    max = element
print(max)

3


## Arrays
A numpy array is a grid of values, **all of the same type**, and is indexed by a tuple of nonnegative integers.
The number of dimensions is the rank of the array;  the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
x = [1,2,3,4,5]
x_np = np.array(x)

print(type(x))
print(type(x_np))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a+3)

[4 5 6]


In [ ]:
print(type(a))            # Prints "<class 'numpy.ndarray'>"

In [ ]:
print(a.shape)            # Prints "(3,)"

(3,)


In [ ]:
print(a)

[1 2 3]


In [ ]:
print(a[0], a[1], a[2])   # Prints "1 2 3"

1 2 3


In [ ]:
a[0] = 5                  # Change an element of the array

In [ ]:
print(a)                  # Prints "[5, 2, 3]"

[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)                     # Prints "(2, 3)"

(2, 3)


In [ ]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

1 2 4


In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(x[1,-1])

6


Numpy also provides many functions to create arrays:


In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.42  0.42]
                             #               [ 0.42  0.42]]"

In [ ]:
f = np.arange(5)  # Create an array with the values from 0 to 4
print(f)          # Prints "[0 1 2 3 4]"

g = np.arange(4.2, 7.1, 0.5)  # Create an array with the values from 4.2 to
                              # 7.1 on steps of 0.5
print(g)                      # Prints "[4.2 4.7 5.2 5.7 6.2 6.7]"

h = np.linspace(10, 20, 5)  # Create an array with 5 equally spaced values
                            # between 10 and 20
print(h)                    # Prints "[[10. 12.5 15. 17.5 20.]"

[0 1 2 3 4]
[4.2 4.7 5.2 5.7 6.2 6.7]
[10.  12.5 15.  17.5 20. ]


We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
x= np.array([ [ [ [1] ],[ [2] ],[ [3] ] ] ]) # 1,3,1,1

z = np.array([[[[1],[2]],[[3],[4]]], [[[1],[2]],[[3],[4]]]])
print(z.shape)

(2, 2, 2, 1)


In [ ]:
x = np.ones((2,3))
print(x)


x = np.zeros((2,3))
print(x)


x = np.random.rand(2,3)
print(x)


x = np.random.randn(2,3)
print(x)


x = np.diag([2,3, 4]) #diagonal matrix
print(x)


x = np.eye(3) #identity matrix
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.40672266 0.85444109 0.74653285]
 [0.01710539 0.00693572 0.56740977]]
[[-0.99493309  1.05285724 -0.1404703 ]
 [ 1.1401348   1.21413982 -0.70244867]]
[[2 0 0]
 [0 3 0]
 [0 0 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
x = np.array([[1], [2]])
y = np.array([[3,4]])
print(x+y)

[[4 5]
 [5 6]]


x is a 2x1 array (2 rows and 1 column).

y is a 1x2 array (1 row and 2 columns).

NumPy will broadcast these arrays to make them compatible for element-wise addition. In this case, it will expand both arrays so that they have the same shape. Here's what happens:

x gets broadcasted to a 2x2 array by repeating its column values:

[[1 1]

  [2 2]]


y gets broadcasted to a 2x2 array by repeating its row values:

[[3 4]

  [3 4]]

In [ ]:
x= np.random.randint(0,9, (4,3))
print(x)

[[7 8 2]
 [5 4 5]
 [4 4 5]
 [3 3 1]]


In [ ]:
y = np.reshape(x, (6, 2))
print(y.shape)

(6, 2)


In [ ]:
print(x)
print(y)

[[7 8 2]
 [5 4 5]
 [4 4 5]
 [3 3 1]]
[[7 8]
 [2 5]
 [4 5]
 [4 4]
 [5 3]
 [3 1]]
